### ISSUE TITLE
General improvements: core.py, numpy_functions.py and tensorflow_functions.py

### ISSUE THREAD

**Issue by moesio-f** [Gabriel-AB/optfuncs#7]
We might want to store the actual functional form as a property in `core.Function`, since it enables us to change it later. Potentially, we could have:
```python
class Function:
  def __init__(self, domain: Domain, fn):
    assert domain is not None
    self._domain = domain
    self._fn = fn

  def __call__(self, x):
    return self._fn(x)

  @property
  def fn(self):
    return self._fn

  @fn.setter
  def fn(self, fn):
    self._fn = fn

  @property
  def domain(self) -> Domain:
    return self._domain

  @domain.setter
  def domain(self, new_domain: Domain):
    self._domain = new_domain

  @property
  def name(self):
    return str(self)

  def __str__(self):
    return self.__class__.__name__
```

There should be different classes for `NumPy` and `TensorFlow` implementations of the functions. Sometimes, it's useful to know whether an instance of a `core.Function` is in `NumPy` or  `TensorFlow`. Additionally, we can find the gradients of a `TensorFlow` function, therefore, there should be a method that enables us to get it directly from the instance. Maybe something like this:
```python
# numpy_functions.py
class NumpyFunction(core.Function):
  def __init__(self, domain: core.Domain, fn):
    super().__init__(domain, fn)

# tensorflow_functions.py
class TensorflowFunction(core.Function):
  def __init__(self, domain: core.Domain, fn, grad_fn):
    super().__init__(domain, fn)
    self._grad_fn = ... # callable that receives a position and returns the gradient and value at this position

  @property
  def grad_fn(self): 
    return self._grad_fn

  @grad_fn.setter
  def grad_fn(self, grad_fn):  # callable that receives a position and returns the gradient and value at this position
    self._grad_fn = grad_fn

  def grads_at(self, x: tf.Tensor):  # returns a tuple containing f(x) and the gradient of f at x
    return self._grad_fn(x)

```

**Comment by Gabriel-AB** [comment]
Add a `_fn` to `core.Function` makes sense to me.
I'm not sure about the gradients, but let's see.

**Comment by Gabriel-AB** [comment]
`_fn` attribute added in 4be12fb2a1be57887a3d9fcc049e67964c043449

**Comment by moesio-f** [comment]
> Add a `_fn` to `core.Function` makes sense to me. I'm not sure about the gradients, but let's see.

I think it would be easier to get the gradients directly from an instance of the function. I mean, instead of calling `tensorflow_functions.get_grads(fn, x)` it would be way easier to call `fn.grads_at(x)` in the code. However, I agree that there's no need to keep a reference to the gradient function (actually, it would be tricky since we would need to change it every time we changed `self._fn`).  I think the code should look like this:

```py
# numpy_functions.py
class NumpyFunction(core.Function):
  def __init__(self, domain: core.Domain):
    super().__init__(domain)

# tensorflow_functions.py
class TensorflowFunction(core.Function):
  def __init__(self, domain: core.Domain):
    super().__init__(domain)

  def grads_at(self, x: tf.Tensor):  # returns a tuple containing f(x) and the gradient of f at x
    return get_grads(self._fn, x) 
```

> `_fn` attribute added in [4be12fb](https://github.com/Gabriel-AB/optfuncs/commit/4be12fb2a1be57887a3d9fcc049e67964c043449)

It looks good. I think it would be better if the `call(...)` method were preceded by `_` (e. g., `_call_ `) to show that it shouldn't change. Also, we should add the getter and setter for the `_fn` attribute.

Do you agree with that, @Gabriel-AB?

**Comment by Gabriel-AB** [comment]
The reason behind the `call` method is to add a easy interface to define a new function
ex:
```python
class NewFunction(core.Function):
  def call(self, x):
    # do something
   return x
``` 
- about the transformed functions: 
if they are supposed to be a statically defined, then the following code should solve the problem:
```python
class TranformedFunction(SomeFunction):
  def call(self, x):
    ...
    x = super().call(x)
    ...
    return x
```

- about the property of `_fn`:
what would be the purpose? Since there is no additional checks or modifications in the get/set of `_fn`, the attribute should be fine without any of those.

- about the grads in the function, seams like a good idea to easily get the gradients by the function

**Comment by Gabriel-AB** [comment]
Possible TensorflowFunction and NumpyFunction implementations in a4638205c19d091a38079c0f9c2918a6c6b2a066
with the gradient interface incorporated in the Tensorflow version

And these are some tests ffaec9dc2b026fa21a78b9bcf0fb7cbbded6ee1f.

---
@moesio-f, let me know what you think about it.
