### ISSUE TITLE
Function transformation module

### ISSUE THREAD

**Issue by moesio-f** [Gabriel-AB/optfuncs#8]
We might want to build functions upon existing functions by means of transformations. That is, we migth want to apply horizontal and/or vertical shifts, reflexions, rotations, stretch/compression and so on.  Maybe we could dynamically create a new class (derived of `core.Function`) upon an existing instance of another class (derived of `core.Function`) and return it.

**Comment by moesio-f** [comment]
Another possibility is to consider a class to represent any transformed function. Thus, we could have a NumPy and Tensorflow version.

**Comment by Gabriel-AB** [comment]
A property looks good, if we store the call function, we can update it after, setting input and output transformations using the ideas of #7 

```python
self.fn = self.call # default function implementation

def __call__(self, x):
  return self.fn(x)

def transform(self, *args):
  def updated(x):
    ... # update with the passed args
    x = self.call(x)
    ...
    return x
  self.fn = updated # tranformed function
```
then the thunder `__call__` just call `fn` and to transform it we update the `fn` in the instance with some `transform()` method and the parameters of the transformation.

**Comment by moesio-f** [comment]
Agreed. However, I  reckon it's better to keep the original function and a transformed version of that function in different classes. 

Currently, a `core.Function` object (instance) represents a function rule (`self._fn` or the `__call__(...)` method) associated with a given domain (`self._domain` and its getters/setters). When we change the function rule, we are, potentially, creating a new `core.Function` (a new function rule associated with a domain). Thus when we apply function transformations, it should be an instance of another class (maybe `TransformedNumpyFunction` or  `TransformedTensorflowFunction`).

Even though I suggested adding getters/setters to the `_fn` attribute (in #7), those should be used cautiously. The main idea of setting `_fn` is to update the function rule to a faster version of the same function (not changing the function rule to a new one). For instance, changing `_fn` to a `tf.function` for running in graph mode.

**Comment by Gabriel-AB** [comment]
In 37e5858fd5426dca596de6782a7b1549588592f7, wrappers for function transformation and gradient calculation were implemented, maybe finishing this issue. 

So, now to, add a function Transformation we just need wrap another function
ex:
```python
import optfuncs 
f = optfuncs.tensorflow_functions.Ackley()
f = optfuncs.wrappers.TransformationWrapper(f, translate_before=10.2, scale_after=0.3) 
```

Using wrappers removed the necessity of the ._fn attribute, and added some classes to work with, which may increase the complexity but, I think the code is more scalable now.
